swagger: "2.0"
info: {}
basePath: /v1
paths:
  /get: {}
  /user/get:
    get:
      tags:
      - user
      description: get user
      operationId: UserController.Get
definitions:
  models.ZDTCustomer.Customer:
    title: Customer
    type: object
